//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace magicfile.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("magicfile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Command line end with an error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMMAN_LINE_END_WITH_ERROR {
            get {
                return ResourceManager.GetString("COMMAN_LINE_END_WITH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save ini-file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED_TO_SAVE_INIFILE {
            get {
                return ResourceManager.GetString("FAILED_TO_SAVE_INIFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILEEXE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILEEXE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INTPUFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("INTPUFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to rename extension from from {0} to {1}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Q_RENAME_EXTENSION {
            get {
                return ResourceManager.GetString("Q_RENAME_EXTENSION", resourceCulture);
            }
        }
    }
}
